Anirudh edits
dimberman/website pull request #1
Opened 2018-06-12 03:11 UTC by dimberman

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.11 Features: set Milestone to 1.11 and Base Branch to release-1.11
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

![Allow edits from maintainers checkbox](https://help.github.com/assets/images/help/pull_requests/allow-maintainers-to-make-edits-sidebar-checkbox.png)

2018-06-12 14:57 UTC, chaimhaas requested changes
Line 35 - end with 'completely independent' - also, capitalize Docker in that last sentence of that line.

2018-06-12 15:07 UTC, chaimhaas requested changes
Line 35 - end with 'completely independent' - also, capitalize Docker in that last sentence of that line.

Line 140 and 144 both say Step 2 - make sure to properly re-number.

2018-06-12 15:07 UTC, chaimhaas requested changes
Line 35 - end with 'completely independent' - also, capitalize Docker in that last sentence of that line.

Line 140 and 144 both say Step 2 - make sure to properly re-number.

2018-06-12 15:08 UTC, chaimhaas requested changes
Line 13 - capitalize Python in 'Python object DAG'

Line 35 - end with 'completely independent' - also, capitalize Docker in that last sentence of that line.

Line 140 and 144 both say Step 2 - make sure to properly re-number.

2018-06-22 17:51 UTC, dimberman commented
@chaimhaas @foxish PTAL

2018-06-25 17:31 UTC, dimberman commented
@chaimhaas acked your comments

2018-06-25 17:45 UTC, foxish commented on content/en/blog/_posts/2018-05-25-Airflow-Kubernetes-Operator.md
> +Since its inception, Airflow's greatest strength has been its flexibility. Airflow offers a wide range of integrations for services ranging from Spark and HBase, to services on Google Cloud Platform
remove `S3`? Or reword to - "services on various cloud providers"

2018-06-25 17:45 UTC, foxish commented on content/en/blog/_posts/2018-05-25-Airflow-Kubernetes-Operator.md
> +Since its inception, Airflow's greatest strength has been its flexibility. Airflow offers a wide range of integrations for services ranging from Spark and HBase, to services on Google Cloud Platform
"If a user wishes to use a different version of SciPy or test a new deep learning framework, they would need to either launch a new Airflow cluster or risk conflicting with the dependencies of other users' workflows."

This is a sudden jump. Can we add a line talking about how such a user may be using airflow first, and then go into how dependency management is hard?

2018-06-25 17:45 UTC, foxish commented on content/en/blog/_posts/2018-05-25-Airflow-Kubernetes-Operator.md
> +To address this issue, we've utilized Kubernetes to allow users to launch arbitrary Docker containers and configurations. Airflow users can now have full power over their run-time environments, resou
arbitrary `Kubernetes pods`? Because the docker operator is different?

2018-06-25 17:45 UTC, foxish commented on content/en/blog/_posts/2018-05-25-Airflow-Kubernetes-Operator.md
> +To address this issue, we've utilized Kubernetes to allow users to launch arbitrary Docker containers and configurations. Airflow users can now have full power over their run-time environments, resou
s/scheduler/workflow orchestrator/

2018-06-25 17:45 UTC, foxish commented on content/en/blog/_posts/2018-05-25-Airflow-Kubernetes-Operator.md
> +There are a multitude on articles on [generating Docker files within a Jenkins build](https://getintodevops.com/blog/building-your-first-Docker-image-with-jenkins-2-guide-for-developers). It's a good
Shall we skip the CI/CD specific part in such detail? It doesn't seem full fledged enough (underspecified in terms of how one can react to the webhook etc) and the example is too simplistic . Maybe we just add a small section about how one *could* use it for CI/CD?

2018-06-25 17:45 UTC, foxish commented on content/en/blog/_posts/2018-05-25-Airflow-Kubernetes-Operator.md
> +Since the Kubernetes Operator is not yet released, we haven't released an official helm chart or operator (however both are currently in progress). However, we are including instructions for a basic
link to helm

2018-06-25 17:45 UTC, foxish commented on content/en/blog/_posts/2018-05-25-Airflow-Kubernetes-Operator.md
> + While this branch is still in the early stages, we hope to see it released for wide release in the next few months.
It's been merged into master right? So s/branch/feature/?

2018-06-25 17:45 UTC, foxish commented on content/en/blog/_posts/2018-05-25-Airflow-Kubernetes-Operator.md
> + * Join our SIG-BIG-DATA meetings on Wednesdays at 10am PT.
s/SIG-BIG-DATA/SIG-BigData/

2018-06-25 17:45 UTC, foxish commented on content/en/blog/_posts/2018-05-25-Airflow-Kubernetes-Operator.md
> +I'd like to thank the Apache Spark and Kubernetes communities, particularly Grant Nicholas, Ben Goldberg, Anirudh Ramanathan, Fokko Dreisprong, and Bolke de Bruin, for your awesome help on these feat
The post starts off with "We..." taking the voice of the community. So, maybe reword to "Special thanks to ..."?

2018-06-28 14:47 UTC, dimberman commented
@chaimhaas @foxish PTAL

2018-06-28 15:34 UTC, foxish commented
Thanks! LGTM from my end. Let's ship it.

2018-06-28 15:53 UTC, merged